apiVersion: v1
kind: Service
metadata:
  name: monitoring-lab-app
spec:
  type: NodePort
  selector:
    app: monitoring-lab-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
